# Generalized Perturbation Theory and Resolvent Operator

using Symbolics
using SymbolicUtils

export apply_resolvent, compute_effective_hamiltonian

"""
    apply_resolvent(H_t::AbstractQuantumOperator, state_projector::ProjectorOp)::AbstractQuantumOperator

Applies the resolvent operator to the intermediate d4 state generated by the kinetic hopping `H_t`.
Instead of dense matrix inversion, it constructs an algebraic sequence that the CAS will reduce
using the `kanamori_resolvent_rules` (yielding the negative energy denominators -\\Delta E_L).
"""
function apply_resolvent(H_t::AbstractQuantumOperator, state_projector::ProjectorOp)::AbstractQuantumOperator
    # The resolvent R = (E_0 - H_0)^{-1} is represented algebraically.
    # It acts on the projected multiplet state: H_t * R * P_L
    return OperatorString([H_t, ResolventOp(), state_projector])
end

"""
    compute_effective_hamiltonian(H_t_minus_1::AbstractQuantumOperator, H_t_plus_1::AbstractQuantumOperator, order::Int)::AbstractQuantumOperator

Executes the Schrieffer-Wolff canonical transformation algebraically.
For order 2: H_eff^(2) = -1/2 * P_low (T_{-1} S_1^{(+)} + S_1^{(-)} T_1) P_low.
"""
function compute_effective_hamiltonian(H_t_minus_1::AbstractQuantumOperator, H_t_plus_1::AbstractQuantumOperator, order::Int)::AbstractQuantumOperator
    if order == 2
        # Generator S_1^{(+)} relies on the resolvent acting on the +1 hopping (creating d4)
        # H_eff = - (T_{-1} * R * T_{+1})
        # We define the AST node. The negative sign comes from the perturbation expansion
        # and the definition of the resolvent denominator.
        resolvent_action = apply_resolvent(H_t_plus_1, IdentityOp()) # Identity acts as sum of P_L
        return ScaledOperator(-1, OperatorString([H_t_minus_1, resolvent_action]))
    elseif order == 3
        # Third order logic for charge density \delta n_l
        # Will be expanded via [S_2, V] + [S_1, T_0] = 0 in future extensions
        return ZeroOp()
    else
        throw(ArgumentError("Schrieffer-Wolff expansion currently only supports order 2 and 3."))
    end
end
