# Generalized Perturbation Theory and Resolvent Operator

using Symbolics

export apply_resolvent, compute_effective_hamiltonian

"""
    apply_resolvent(H_t::OperatorSum, U::Num, JH::Num)::OperatorSum

Applies the resolvent operator \\mathcal{R} to the intermediate d4 state generated by `H_t`.
It splits the generic double-occupancy projector P^(2) into the invariant L=0,1,2 Kanamori 
multiplet channels and injects the exact analytical negative energy denominators -1/\\Delta E_L.
"""
function apply_resolvent(H_t::OperatorSum, U::Num, JH::Num)::OperatorSum
    # Retrieve analytical exact energies from the Kanamori module
    # Dict(MultipletProjector(L) => \\Delta E_L)
    # Using hardcoded resolution here to avoid circular module dependencies during tests
    eigen_dict = Dict(
        0 => U + 2*JH,
        1 => U - 3*JH,
        2 => U - JH
    )
    
    resolved_terms = AbstractQuantumOperator[]
    
    for term in H_t.terms
        # Assuming term is ScaledOperator(scalar, OperatorString([... P^(2) ...]))
        if term isa ScaledOperator && term.op isa OperatorString
            factors = term.op.factors
            
            # Locate the ParticleProjector(2) which indicates the d4 intermediate state
            p2_idx = findfirst(x -> x isa ParticleProjector && x.holes == 2, factors)
            
            if p2_idx !== nothing
                # Spectral resolution: Split the term into the 3 multiplet channels
                for L in [0, 1, 2]
                    channel_proj = MultipletProjector(L)
                    energy_penalty = -1 / eigen_dict[L] # (E_0 - H_0)^{-1}
                    
                    new_factors = copy(factors)
                    new_factors[p2_idx] = channel_proj
                    
                    # Inject the energy penalty into the scalar coefficient
                    new_scalar = term.scalar * energy_penalty
                    
                    push!(resolved_terms, ScaledOperator(new_scalar, OperatorString(new_factors)))
                end
            else
                push!(resolved_terms, term)
            end
        end
    end
    
    return OperatorSum(resolved_terms)
end

"""
    compute_effective_hamiltonian(Tm1::OperatorSum, T1::OperatorSum, U::Num, JH::Num)::OperatorSum

Executes the canonical transformation algebraically: H_eff^(2) = T_{-1} \\mathcal{R} T_1.
Distributes the operator sums and applies the orthogonal pruning rules.
"""
function compute_effective_hamiltonian(Tm1::OperatorSum, T1::OperatorSum, U::Num, JH::Num)::OperatorSum
    # 1. Apply the resolvent to T1 to generate \\mathcal{R} T_1
    R_T1 = apply_resolvent(T1, U, JH)
    
    # 2. Distribute T_{-1} * (\\mathcal{R} T_1)
    h_eff_terms = AbstractQuantumOperator[]
    
    for left_term in Tm1.terms
        for right_term in R_T1.terms
            if left_term isa ScaledOperator && right_term isa ScaledOperator
                # Combine scalars
                combined_scalar = left_term.scalar * right_term.scalar
                
                # Concatenate operator strings
                left_factors = left_term.op isa OperatorString ? left_term.op.factors : [left_term.op]
                right_factors = right_term.op isa OperatorString ? right_term.op.factors : [right_term.op]
                
                combined_string = OperatorString(vcat(left_factors, right_factors))
                
                # Apply algebraic pruning (e.g., P_L * P_L' = \\delta_{LL'})
                pruned = apply_algebraic_rules(combined_string.factors)
                
                if length(pruned) == 1 && pruned[1] isa ZeroOp
                    continue # Orthogonality annihilated this branch
                end
                
                push!(h_eff_terms, ScaledOperator(combined_scalar, OperatorString(pruned)))
            end
        end
    end
    
    return OperatorSum(h_eff_terms)
end
